// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: link/v1/link.proto

package linkv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShortLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ExpireAfter   string                 `protobuf:"bytes,2,opt,name=expire_after,json=expireAfter,proto3" json:"expire_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkRequest) Reset() {
	*x = CreateShortLinkRequest{}
	mi := &file_link_v1_link_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkRequest) ProtoMessage() {}

func (x *CreateShortLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateShortLinkRequest) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortLinkRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *CreateShortLinkRequest) GetExpireAfter() string {
	if x != nil {
		return x.ExpireAfter
	}
	return ""
}

type ShortLinkResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShortUrl      string                  `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                  `protobuf:"bytes,3,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ShortCode     string                  `protobuf:"bytes,4,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	UserId        *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpireAt      string                  `protobuf:"bytes,6,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	IsActive      bool                    `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortLinkResponse) Reset() {
	*x = ShortLinkResponse{}
	mi := &file_link_v1_link_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortLinkResponse) ProtoMessage() {}

func (x *ShortLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortLinkResponse.ProtoReflect.Descriptor instead.
func (*ShortLinkResponse) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{1}
}

func (x *ShortLinkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShortLinkResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *ShortLinkResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *ShortLinkResponse) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *ShortLinkResponse) GetUserId() *wrapperspb.StringValue {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *ShortLinkResponse) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

func (x *ShortLinkResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetShortLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortLinkRequest) Reset() {
	*x = GetShortLinkRequest{}
	mi := &file_link_v1_link_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortLinkRequest) ProtoMessage() {}

func (x *GetShortLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortLinkRequest.ProtoReflect.Descriptor instead.
func (*GetShortLinkRequest) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{2}
}

func (x *GetShortLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RedirectLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectLinkRequest) Reset() {
	*x = RedirectLinkRequest{}
	mi := &file_link_v1_link_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectLinkRequest) ProtoMessage() {}

func (x *RedirectLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectLinkRequest.ProtoReflect.Descriptor instead.
func (*RedirectLinkRequest) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{3}
}

func (x *RedirectLinkRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type RedirectLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectLinkResponse) Reset() {
	*x = RedirectLinkResponse{}
	mi := &file_link_v1_link_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectLinkResponse) ProtoMessage() {}

func (x *RedirectLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectLinkResponse.ProtoReflect.Descriptor instead.
func (*RedirectLinkResponse) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{4}
}

func (x *RedirectLinkResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type DeleteShortLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShortLinkRequest) Reset() {
	*x = DeleteShortLinkRequest{}
	mi := &file_link_v1_link_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShortLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortLinkRequest) ProtoMessage() {}

func (x *DeleteShortLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteShortLinkRequest) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteShortLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteShortLinkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteShortLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShortLinkResponse) Reset() {
	*x = DeleteShortLinkResponse{}
	mi := &file_link_v1_link_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShortLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortLinkResponse) ProtoMessage() {}

func (x *DeleteShortLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortLinkResponse.ProtoReflect.Descriptor instead.
func (*DeleteShortLinkResponse) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteShortLinkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListShortLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShortLinksRequest) Reset() {
	*x = ListShortLinksRequest{}
	mi := &file_link_v1_link_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShortLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShortLinksRequest) ProtoMessage() {}

func (x *ListShortLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShortLinksRequest.ProtoReflect.Descriptor instead.
func (*ListShortLinksRequest) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{7}
}

func (x *ListShortLinksRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListShortLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*ShortLinkResponse   `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShortLinksResponse) Reset() {
	*x = ListShortLinksResponse{}
	mi := &file_link_v1_link_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShortLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShortLinksResponse) ProtoMessage() {}

func (x *ListShortLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShortLinksResponse.ProtoReflect.Descriptor instead.
func (*ListShortLinksResponse) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{8}
}

func (x *ListShortLinksResponse) GetLinks() []*ShortLinkResponse {
	if x != nil {
		return x.Links
	}
	return nil
}

// --- Статистика по ссылке ---
type GetLinkStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortLinkId   string                 `protobuf:"bytes,1,opt,name=short_link_id,json=shortLinkId,proto3" json:"short_link_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkStatsRequest) Reset() {
	*x = GetLinkStatsRequest{}
	mi := &file_link_v1_link_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkStatsRequest) ProtoMessage() {}

func (x *GetLinkStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkStatsRequest.ProtoReflect.Descriptor instead.
func (*GetLinkStatsRequest) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{9}
}

func (x *GetLinkStatsRequest) GetShortLinkId() string {
	if x != nil {
		return x.ShortLinkId
	}
	return ""
}

type LinkStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *DetailedLinkStats     `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkStatsResponse) Reset() {
	*x = LinkStatsResponse{}
	mi := &file_link_v1_link_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkStatsResponse) ProtoMessage() {}

func (x *LinkStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkStatsResponse.ProtoReflect.Descriptor instead.
func (*LinkStatsResponse) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{10}
}

func (x *LinkStatsResponse) GetStats() *DetailedLinkStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type DetailedLinkStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Total          int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	UniqueIpCount  int64                  `protobuf:"varint,2,opt,name=unique_ip_count,json=uniqueIpCount,proto3" json:"unique_ip_count,omitempty"`
	UniqueIps      []string               `protobuf:"bytes,3,rep,name=unique_ips,json=uniqueIps,proto3" json:"unique_ips,omitempty"`
	CountriesCount int32                  `protobuf:"varint,4,opt,name=countries_count,json=countriesCount,proto3" json:"countries_count,omitempty"`
	Countries      []string               `protobuf:"bytes,5,rep,name=countries,proto3" json:"countries,omitempty"`
	CountriesStats map[string]int64       `protobuf:"bytes,6,rep,name=countries_stats,json=countriesStats,proto3" json:"countries_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	DailyStats     map[string]int64       `protobuf:"bytes,7,rep,name=daily_stats,json=dailyStats,proto3" json:"daily_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DetailedLinkStats) Reset() {
	*x = DetailedLinkStats{}
	mi := &file_link_v1_link_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailedLinkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailedLinkStats) ProtoMessage() {}

func (x *DetailedLinkStats) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailedLinkStats.ProtoReflect.Descriptor instead.
func (*DetailedLinkStats) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{11}
}

func (x *DetailedLinkStats) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DetailedLinkStats) GetUniqueIpCount() int64 {
	if x != nil {
		return x.UniqueIpCount
	}
	return 0
}

func (x *DetailedLinkStats) GetUniqueIps() []string {
	if x != nil {
		return x.UniqueIps
	}
	return nil
}

func (x *DetailedLinkStats) GetCountriesCount() int32 {
	if x != nil {
		return x.CountriesCount
	}
	return 0
}

func (x *DetailedLinkStats) GetCountries() []string {
	if x != nil {
		return x.Countries
	}
	return nil
}

func (x *DetailedLinkStats) GetCountriesStats() map[string]int64 {
	if x != nil {
		return x.CountriesStats
	}
	return nil
}

func (x *DetailedLinkStats) GetDailyStats() map[string]int64 {
	if x != nil {
		return x.DailyStats
	}
	return nil
}

// --- Клики по ссылке ---
type GetLinkClicksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortLinkId   string                 `protobuf:"bytes,1,opt,name=short_link_id,json=shortLinkId,proto3" json:"short_link_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkClicksRequest) Reset() {
	*x = GetLinkClicksRequest{}
	mi := &file_link_v1_link_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkClicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkClicksRequest) ProtoMessage() {}

func (x *GetLinkClicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkClicksRequest.ProtoReflect.Descriptor instead.
func (*GetLinkClicksRequest) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{12}
}

func (x *GetLinkClicksRequest) GetShortLinkId() string {
	if x != nil {
		return x.ShortLinkId
	}
	return ""
}

type GetLinkClicksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clicks        []*Click               `protobuf:"bytes,1,rep,name=clicks,proto3" json:"clicks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkClicksResponse) Reset() {
	*x = GetLinkClicksResponse{}
	mi := &file_link_v1_link_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkClicksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkClicksResponse) ProtoMessage() {}

func (x *GetLinkClicksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkClicksResponse.ProtoReflect.Descriptor instead.
func (*GetLinkClicksResponse) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{13}
}

func (x *GetLinkClicksResponse) GetClicks() []*Click {
	if x != nil {
		return x.Clicks
	}
	return nil
}

type Click struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	ClickedAt     string                 `protobuf:"bytes,4,opt,name=clicked_at,json=clickedAt,proto3" json:"clicked_at,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Click) Reset() {
	*x = Click{}
	mi := &file_link_v1_link_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Click) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Click) ProtoMessage() {}

func (x *Click) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Click.ProtoReflect.Descriptor instead.
func (*Click) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{14}
}

func (x *Click) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Click) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Click) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Click) GetClickedAt() string {
	if x != nil {
		return x.ClickedAt
	}
	return ""
}

func (x *Click) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Click) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

var File_link_v1_link_proto protoreflect.FileDescriptor

const file_link_v1_link_proto_rawDesc = "" +
	"\n" +
	"\x12link/v1/link.proto\x12\alink.v1\x1a\x17validate/validate.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x87\x01\n" +
	"\x16CreateShortLinkRequest\x120\n" +
	"\foriginal_url\x18\x01 \x01(\tB\r\xfaB\n" +
	"r\b\x10\x05\x18\x80\x10\x88\x01\x01R\voriginalUrl\x12;\n" +
	"\fexpire_after\x18\x02 \x01(\tB\x18\xfaB\x15r\x13\x18\x102\x0f^[0-9]+[smhdw]$R\vexpireAfter\"\xa6\x02\n" +
	"\x11ShortLinkResponse\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\x12%\n" +
	"\tshort_url\x18\x02 \x01(\tB\b\xfaB\x05r\x03\x88\x01\x01R\bshortUrl\x12+\n" +
	"\foriginal_url\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x88\x01\x01R\voriginalUrl\x12(\n" +
	"\n" +
	"short_code\x18\x04 \x01(\tB\t\xfaB\x06r\x04\x10\x04\x18 R\tshortCode\x12?\n" +
	"\auser_id\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12\x1b\n" +
	"\texpire_at\x18\x06 \x01(\tR\bexpireAt\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\"/\n" +
	"\x13GetShortLinkRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\"?\n" +
	"\x13RedirectLinkRequest\x12(\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x04\x18 R\tshortCode\"C\n" +
	"\x14RedirectLinkResponse\x12+\n" +
	"\foriginal_url\x18\x01 \x01(\tB\b\xfaB\x05r\x03\x88\x01\x01R\voriginalUrl\"U\n" +
	"\x16DeleteShortLinkRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\x12!\n" +
	"\auser_id\x18\x02 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\"=\n" +
	"\x17DeleteShortLinkResponse\x12\"\n" +
	"\amessage\x18\x01 \x01(\tB\b\xfaB\x05r\x03\x18\x80\x02R\amessage\":\n" +
	"\x15ListShortLinksRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\"J\n" +
	"\x16ListShortLinksResponse\x120\n" +
	"\x05links\x18\x01 \x03(\v2\x1a.link.v1.ShortLinkResponseR\x05links\"C\n" +
	"\x13GetLinkStatsRequest\x12,\n" +
	"\rshort_link_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\vshortLinkId\"E\n" +
	"\x11LinkStatsResponse\x120\n" +
	"\x05stats\x18\x01 \x01(\v2\x1a.link.v1.DetailedLinkStatsR\x05stats\"\xdf\x03\n" +
	"\x11DetailedLinkStats\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12&\n" +
	"\x0funique_ip_count\x18\x02 \x01(\x03R\runiqueIpCount\x12\x1d\n" +
	"\n" +
	"unique_ips\x18\x03 \x03(\tR\tuniqueIps\x12'\n" +
	"\x0fcountries_count\x18\x04 \x01(\x05R\x0ecountriesCount\x12\x1c\n" +
	"\tcountries\x18\x05 \x03(\tR\tcountries\x12W\n" +
	"\x0fcountries_stats\x18\x06 \x03(\v2..link.v1.DetailedLinkStats.CountriesStatsEntryR\x0ecountriesStats\x12K\n" +
	"\vdaily_stats\x18\a \x03(\v2*.link.v1.DetailedLinkStats.DailyStatsEntryR\n" +
	"dailyStats\x1aA\n" +
	"\x13CountriesStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a=\n" +
	"\x0fDailyStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"D\n" +
	"\x14GetLinkClicksRequest\x12,\n" +
	"\rshort_link_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\vshortLinkId\"?\n" +
	"\x15GetLinkClicksResponse\x12&\n" +
	"\x06clicks\x18\x01 \x03(\v2\x0e.link.v1.ClickR\x06clicks\"\xc6\x01\n" +
	"\x05Click\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\x12\x17\n" +
	"\x02ip\x18\x02 \x01(\tB\a\xfaB\x04r\x02p\x01R\x02ip\x12'\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\x80\x02R\tuserAgent\x12\x1d\n" +
	"\n" +
	"clicked_at\x18\x04 \x01(\tR\tclickedAt\x12!\n" +
	"\acountry\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x18@R\acountry\x12\x1f\n" +
	"\x06region\x18\x06 \x01(\tB\a\xfaB\x04r\x02\x18@R\x06region2\xb7\x04\n" +
	"\vLinkService\x12N\n" +
	"\x0fCreateShortLink\x12\x1f.link.v1.CreateShortLinkRequest\x1a\x1a.link.v1.ShortLinkResponse\x12H\n" +
	"\fGetShortLink\x12\x1c.link.v1.GetShortLinkRequest\x1a\x1a.link.v1.ShortLinkResponse\x12K\n" +
	"\fRedirectLink\x12\x1c.link.v1.RedirectLinkRequest\x1a\x1d.link.v1.RedirectLinkResponse\x12T\n" +
	"\x0fDeleteShortLink\x12\x1f.link.v1.DeleteShortLinkRequest\x1a .link.v1.DeleteShortLinkResponse\x12Q\n" +
	"\x0eListShortLinks\x12\x1e.link.v1.ListShortLinksRequest\x1a\x1f.link.v1.ListShortLinksResponse\x12H\n" +
	"\fGetLinkStats\x12\x1c.link.v1.GetLinkStatsRequest\x1a\x1a.link.v1.LinkStatsResponse\x12N\n" +
	"\rGetLinkClicks\x12\x1d.link.v1.GetLinkClicksRequest\x1a\x1e.link.v1.GetLinkClicksResponseB5Z3github.com/Anabol1ks/linkvault-proto/link/v1;linkv1b\x06proto3"

var (
	file_link_v1_link_proto_rawDescOnce sync.Once
	file_link_v1_link_proto_rawDescData []byte
)

func file_link_v1_link_proto_rawDescGZIP() []byte {
	file_link_v1_link_proto_rawDescOnce.Do(func() {
		file_link_v1_link_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_link_v1_link_proto_rawDesc), len(file_link_v1_link_proto_rawDesc)))
	})
	return file_link_v1_link_proto_rawDescData
}

var file_link_v1_link_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_link_v1_link_proto_goTypes = []any{
	(*CreateShortLinkRequest)(nil),  // 0: link.v1.CreateShortLinkRequest
	(*ShortLinkResponse)(nil),       // 1: link.v1.ShortLinkResponse
	(*GetShortLinkRequest)(nil),     // 2: link.v1.GetShortLinkRequest
	(*RedirectLinkRequest)(nil),     // 3: link.v1.RedirectLinkRequest
	(*RedirectLinkResponse)(nil),    // 4: link.v1.RedirectLinkResponse
	(*DeleteShortLinkRequest)(nil),  // 5: link.v1.DeleteShortLinkRequest
	(*DeleteShortLinkResponse)(nil), // 6: link.v1.DeleteShortLinkResponse
	(*ListShortLinksRequest)(nil),   // 7: link.v1.ListShortLinksRequest
	(*ListShortLinksResponse)(nil),  // 8: link.v1.ListShortLinksResponse
	(*GetLinkStatsRequest)(nil),     // 9: link.v1.GetLinkStatsRequest
	(*LinkStatsResponse)(nil),       // 10: link.v1.LinkStatsResponse
	(*DetailedLinkStats)(nil),       // 11: link.v1.DetailedLinkStats
	(*GetLinkClicksRequest)(nil),    // 12: link.v1.GetLinkClicksRequest
	(*GetLinkClicksResponse)(nil),   // 13: link.v1.GetLinkClicksResponse
	(*Click)(nil),                   // 14: link.v1.Click
	nil,                             // 15: link.v1.DetailedLinkStats.CountriesStatsEntry
	nil,                             // 16: link.v1.DetailedLinkStats.DailyStatsEntry
	(*wrapperspb.StringValue)(nil),  // 17: google.protobuf.StringValue
}
var file_link_v1_link_proto_depIdxs = []int32{
	17, // 0: link.v1.ShortLinkResponse.user_id:type_name -> google.protobuf.StringValue
	1,  // 1: link.v1.ListShortLinksResponse.links:type_name -> link.v1.ShortLinkResponse
	11, // 2: link.v1.LinkStatsResponse.stats:type_name -> link.v1.DetailedLinkStats
	15, // 3: link.v1.DetailedLinkStats.countries_stats:type_name -> link.v1.DetailedLinkStats.CountriesStatsEntry
	16, // 4: link.v1.DetailedLinkStats.daily_stats:type_name -> link.v1.DetailedLinkStats.DailyStatsEntry
	14, // 5: link.v1.GetLinkClicksResponse.clicks:type_name -> link.v1.Click
	0,  // 6: link.v1.LinkService.CreateShortLink:input_type -> link.v1.CreateShortLinkRequest
	2,  // 7: link.v1.LinkService.GetShortLink:input_type -> link.v1.GetShortLinkRequest
	3,  // 8: link.v1.LinkService.RedirectLink:input_type -> link.v1.RedirectLinkRequest
	5,  // 9: link.v1.LinkService.DeleteShortLink:input_type -> link.v1.DeleteShortLinkRequest
	7,  // 10: link.v1.LinkService.ListShortLinks:input_type -> link.v1.ListShortLinksRequest
	9,  // 11: link.v1.LinkService.GetLinkStats:input_type -> link.v1.GetLinkStatsRequest
	12, // 12: link.v1.LinkService.GetLinkClicks:input_type -> link.v1.GetLinkClicksRequest
	1,  // 13: link.v1.LinkService.CreateShortLink:output_type -> link.v1.ShortLinkResponse
	1,  // 14: link.v1.LinkService.GetShortLink:output_type -> link.v1.ShortLinkResponse
	4,  // 15: link.v1.LinkService.RedirectLink:output_type -> link.v1.RedirectLinkResponse
	6,  // 16: link.v1.LinkService.DeleteShortLink:output_type -> link.v1.DeleteShortLinkResponse
	8,  // 17: link.v1.LinkService.ListShortLinks:output_type -> link.v1.ListShortLinksResponse
	10, // 18: link.v1.LinkService.GetLinkStats:output_type -> link.v1.LinkStatsResponse
	13, // 19: link.v1.LinkService.GetLinkClicks:output_type -> link.v1.GetLinkClicksResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_link_v1_link_proto_init() }
func file_link_v1_link_proto_init() {
	if File_link_v1_link_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_link_v1_link_proto_rawDesc), len(file_link_v1_link_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_link_v1_link_proto_goTypes,
		DependencyIndexes: file_link_v1_link_proto_depIdxs,
		MessageInfos:      file_link_v1_link_proto_msgTypes,
	}.Build()
	File_link_v1_link_proto = out.File
	file_link_v1_link_proto_goTypes = nil
	file_link_v1_link_proto_depIdxs = nil
}
